### ISSUE TITLE
privoxy configuration file has moved

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#107]
The file for configuration of privoxy has changed from /etc/privoxy/config to /etc/config/privoxy, so that it works properly with uci.  This happened in OpenWRT Chaos Calmer, so proxy.sh needs to be fixed to work with the new file structure.

**Comment by taobaodog** [comment]
i think it can be closed. isn`t it?

**Comment by wmhaynes** [comment]
Proxy still isn't working and it's because the config file is wrong, I
believe.  I'll take a look at it.


Sincerely,

*William Haynes*
Chief Executive Officer / Founder
Sabai Technology <http://www.sabaitechnology.com/> | RouterSource.com
<http://routersource.com/>
+1
864.962.4072 | +1 864.962.4073

[image: Sabai Technology] <http://www.sabaitechnology.com>  [image: William
Haynes] <https://www.linkedin.com/in/sabaitechnology>  [image: Twitter]
<https://twitter.com/sabaitechnology>  [image: Facebook]
<https://www.facebook.com/sabairouters>
