### ISSUE TITLE
OpenVPN Log not showing

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#130]
The OpenVPN page has a "Show Log" button, which is currently showing "no file".  It should show the openvpn log or openvpn contents of /var/log/messenger.

**Comment by wmhaynes** [comment]
Fixed for now by using openvpn contents of /var/log/messenger written to /etc/sabai/openvpn/ovpn.log file and showing that.  May be the way to do it long term, just not sure why standard openvpn logging into a separate file doesn't seem to be working.

**Comment by taobaodog** [comment]
Now file is present and its lines are shown in reverse order as you wished.

**Comment by wmhaynes** [comment]
Now my openvpn log is showing blank.

**Comment by wmhaynes** [comment]
Fri Jan 22 13:05:51 2016 daemon.err uhttpd[1828]: sed: /var/log/ovpn.log: No such file or directory
Fri Jan 22 13:06:01 2016 daemon.err uhttpd[1828]: sed: /var/log/ovpn.log: No such file or directory

Thinking the file needs to be created by touch if it doesn't exist, so that logging can occur.

**Comment by taobaodog** [comment]
Hello William,

Thank you for your testing. Ovpn doesn't log to file, if there are no log
parameters set in configuration file. That is why I added new part of code
in ovpn.sh
https://github.com/sabaitechnology/SabaiOpen/commit/4b0a389a90cf365787397aba54f73142b90f9109
lines 121-126. It must automatically create log file, if those lines are
added to config. Please, check presence of this lines in your build and let
me know.

P.S. if it is not difficult to you, please change log-append -> log in
ovpn.current config, restart ovpn and check if ovpn.log is present.
23 янв. 2016 г. 3:24 пользователь "William Haynes" <notifications@github.com>
написал:

**Comment by wmhaynes** [comment]
The 5 lines were there.  When I added append-log to the ovpn.current, then
logging occurred correctly.

Sincerely,

*William Haynes*
Chief Executive Officer / Founder
Sabai Technology <http://www.sabaitechnology.com/> | RouterSource.com
<http://routersource.com/>
+1
864.962.4072 | +1 864.962.4073

[image: Sabai Technology] <http://www.sabaitechnology.com>  [image: William
Haynes] <https://www.linkedin.com/in/sabaitechnology>  [image: Twitter]
<https://twitter.com/sabaitechnology>  [image: Facebook]
<https://www.facebook.com/sabairouters>
