### ISSUE TITLE
OpenVPN Scramble needs to be added to code

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#143]
This was done on Tomato already.  I believe this patch was used?  https://github.com/clayface/openvpn_xorpatch

We need to patch the openvpn 2.3.6 to allow for use of scramble.

**Comment by taobaodog** [comment]
Patch was added.
 Need to fix:

Fri Jan 29 10:20:04 2016 daemon.err openvpn(sabai)[2601]: Options error: Unrecognized option or missing parameter(s) in /etc/sabai/openvpn/ovpn.current:23: explicit-exit-notify (2.3.6)

**Comment by taobaodog** [comment]
Keep in mind that you have to comment out the line "explicit-exit-notify 2" (From Ruth' letter)
