### ISSUE TITLE
LAN of 99 causing issues?

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#191]
Status page should be showing WAN IP but is showing LAN IP.  Also, I thought that LAN was going to be missing from VPNA?
![bad info](https://cloud.githubusercontent.com/assets/1651880/13081075/5f6c8766-d499-11e5-8c4b-cb696178b9ac.png)

**Comment by taobaodog** [comment]
Lan was removed. So no issue for now.
