### ISSUE TITLE
New VPNA login screen changes

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#213]
Please make the changes as shown in the attached screen shots.
![image 3](https://cloud.githubusercontent.com/assets/15368845/13987580/9fca7ec4-f0de-11e5-99c8-c9842d32b398.png)
![image 2](https://cloud.githubusercontent.com/assets/15368845/13987582/a1329012-f0de-11e5-9eca-c78b4e650a19.png)

**Comment by taobaodog** [comment]
color changed
