### ISSUE TITLE
Need to be able to renew the DHCP without reboot

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#227]
I would like to have a button that can be pressed to renew the lease with the router. In many cases, especially with upgrades/etc, the new VPNA will show up as a different IP address and it has to be manually changed in the router device list. When that happens, currently there is no way to renew the lease without doing a reboot.

**Comment by wmhaynes** [comment]
You can put a button on the status page in the WAN that says "Renew DHCP".  When the button is pushed, it would do the following:
sudo dhclient -v -r eth0
sudo dhclient -v eth0
