### ISSUE TITLE
Line removal

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#232]
Some VPN providers have the following line in their OpenVPN config files. We have to manually remove it. Can we possibly have the VPNA do it automatically?

crl-verify crl.pem

Thanks!

**Comment by wmhaynes** [comment]
https://github.com/sabaitechnology/SabaiOpen/commit/d5a6052861291206752eac34c993a0e3c66b92bd is the changed that addressed this.
