### ISSUE TITLE
Automatic Upgrade not working consistently

### ISSUE THREAD

**Issue by wmhaynes** [sabaitechnology/SabaiOpen#297]
On 3.0.4, upgrade has to be done manually.  Automatic upgrade is not working properly.  Gives Error 02.

**Comment by taobaodog** [comment]
It seems, that sometimes file is downloaded not completely .

**Comment by taobaodog** [comment]
It was increased server side timeout and frontend timeout. 
We need to get log when it breaks. Can't reproduce on my side.

**Comment by wmhaynes** [comment]
This was a problem with syntax and should be fixed now.
