### ISSUE TITLE
Old version showing as available as an update

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#316]
Current version shows as 3.0.4 SomChai 06-22-16_06-26 but on the Upgrade page it shows New available version 3.0.3. Server Update reports no new version if I click it. I have tried a factory reset. I am now doing a manual upgrade again. Did not change after manual upgrade.
![2016-08-03 10_56_58-gotoassist](https://cloud.githubusercontent.com/assets/15368845/17370401/f056d3a8-5969-11e6-9a52-5b3735c32f62.png)
![2016-08-03 10_57_11-gotoassist](https://cloud.githubusercontent.com/assets/15368845/17370404/f234ed0e-5969-11e6-9cd3-07d30b67e697.png)

**Comment by taobaodog** [comment]
Ruth, i ask you for now to fi x it with these command:
uci set sabai.general.new_version=""
uci commit sabai

I made for coming update.
