### ISSUE TITLE
Default IP address changed

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#336]
Default IP Address needs to be 192.168.199.1 and not 192.168.99.1

**Comment by taobaodog** [comment]
Will be fixed after beta testing. It was made for debug beta version.

**Comment by ruthpetty** [comment]
After testing this I feel that leaving it at 99.1 is probably our best option as many folks will still use their Sabai router along with this because of the superior WiFi capabilities. Leaving it at 99.1 will avoid any conflicts.
Thanks!
