### ISSUE TITLE
PPTP does not work

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#337]
PPTP will not start

**Comment by ruthpetty** [comment]
Log when I attempt to start PPTP

Thu Sep 15 15:11:26 2016 daemon.notice netifd: Interface 'vpn' is now down
Thu Sep 15 15:11:26 2016 daemon.notice netifd: Interface 'vpn' is setting up now
Thu Sep 15 15:11:26 2016 daemon.info pppd[6824]: Plugin pptp.so loaded.
Thu Sep 15 15:11:26 2016 daemon.info pppd[6824]: PPTP plugin version 1.00
Thu Sep 15 15:11:26 2016 daemon.err pppd[6824]: invalid parameter '' for mppe option
Thu Sep 15 15:11:26 2016 daemon.notice netifd: vpn (6824): /usr/sbin/pppd: invalid parameter '' for mppe option
Thu Sep 15 15:11:26 2016 user.notice root: pptp is disconnected.
Thu Sep 15 15:11:26 2016 daemon.notice netifd: Interface 'vpn' is now down
Thu Sep 15 15:11:28 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:33 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:36 2016 user.notice root: pptp is disconnected.
Thu Sep 15 15:11:38 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:43 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:46 2016 user.notice root: pptp is disconnected.
Thu Sep 15 15:11:48 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:53 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:56 2016 user.notice root: pptp is disconnected.
Thu Sep 15 15:11:56 2016 daemon.err uhttpd[1988]: ifconfig: pptp-vpn: error fetching interface information: Device not found
Thu Sep 15 15:11:56 2016 daemon.err miniupnpd[2361]: ioctl(s, SIOCGIFADDR, ...): Cannot assign requested address
Thu Sep 15 15:11:56 2016 daemon.err miniupnpd[2361]: Failed to get IP for interface eth0
Thu Sep 15 15:11:56 2016 daemon.warn miniupnpd[2361]: SendNATPMPPublicAddressChangeNotification: cannot get public IP address, stopping
Thu Sep 15 15:11:56 2016 daemon.warn dnsmasq[2312]: failed to access /tmp/resolv.conf.vpn: No such file or directory
Thu Sep 15 15:11:56 2016 user.notice root: NO VPN route table was added.
Thu Sep 15 15:11:56 2016 user.notice root: DNS is default.
Thu Sep 15 15:11:56 2016 user.notice root: PPTP is stopped.

**Comment by taobaodog** [comment]
Kasper, please, add validation to MPPE-128 select element.

**Comment by taobaodog** [comment]
Ruth, please select something before start pptp. Acctually it works.
