### ISSUE TITLE
WiFi Radio Channel Width

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#347]
Need to change the text from
HT20 and HT40 
![unnamed](https://cloud.githubusercontent.com/assets/15368845/18561770/3de11cee-7b4f-11e6-8705-012a4d4e9f60.png)
to
20MHz and 40MHz
![unnamed 1](https://cloud.githubusercontent.com/assets/15368845/18561769/3de0866c-7b4f-11e6-80b1-266699fd7580.png)

**Comment by taobaodog** [comment]
Specifies the channel width in 802.11n and 802.11ac mode, possible values are:
HT20 (single 20MHz channel),
HT40- (2x 20MHz channels, primary/control channel is upper, secondary channel is below)
HT40+ (2x 20MHz channels, primary/control channel is lower, secondary channel is above).
HT40 (2x 20Mz channels, auto selection of upper or lower secondary channel on versions 14.07 and above). 
NONE (disables 802.11n rates and enforce the usage of legacy 802.11 b/g/a rates)

It is not about 20-40 MHz
