### ISSUE TITLE
Port Forwarding multiple ports to same device

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#353]
Unable to port forward more than one port to a single device. For example, I need to port forward 943 and 1194 for a device on the network to be able to function. I am only able to enter one or the other, not both. I get a message 
![screenshot from 2016-10-19 14_11_02](https://cloud.githubusercontent.com/assets/15368845/19531785/f997cfec-9606-11e6-87fe-89cd88b1bf19.png)
![screenshot from 2016-10-19 14_11_32](https://cloud.githubusercontent.com/assets/15368845/19531790/fc35abfc-9606-11e6-99bf-e18f7d74e241.png)

**Comment by KasperOlesen** [comment]
I completely forgot to take this usecase into consideration. I will fix it.
