### ISSUE TITLE
Gateways wording

### ISSUE THREAD

**Issue by ruthpetty** [sabaitechnology/SabaiOpen#363]
The explanations at the bottom do not match the option names:
Terms need to match and need to be in the order in which they are displayed on the screen. In addition, a qualifier needs to be added to the top of the term explanations. 
As example:

**Click a device entry and click Edit to adjust the information provided:**
IP Address: The IP address assigned to the device. You can click in this field and change the IP address. 
MAC: The hardware address of the unit. This is hardcoded into the device. 
Name: The name of the device. You can click in this field and change the name. 
Static: Choose "on" to make lease permanent. 
Expiration time: The time when the lease expires.
Status: Current status of the device
Routing option: Choose the default route for this device. "vpn_fallback" will continue access through internet if VPN is down. 

![2016-11-08 13_32_48-sabaiopen - network_ dhcp_gateways](https://cloud.githubusercontent.com/assets/15368845/20112348/0bdc1a2e-a5ba-11e6-95de-9347b46ddfee.png)

**Comment by wmhaynes** [comment]
Changed wording to match table.
